### ISSUE TITLE
As a user, I want to be able to access Support resources.

### ISSUE THREAD

**Issue by kkennis** [PeggyJV/il-loss-charts#104]
New User Story for Support: As a user who is on the sommelier site, I want to see a “Support” icon at the bottom right of the screen like https://image.flaticon.com/icons/png/512/69/69114.png that will link to our Support channel in Discord with the following link: https://discord.gg/VXyUgtnbtv so that I will be able to go to Discord and ask my support questions.

**Comment by taariq** [comment]
Thank you! Yeup. We think this will be great to grow the community and collect insights on how folks are viewing the app. Thank you! Let's go!

**Comment by kkennis** [comment]
On the site thanks to @luckyOdisetti
