### ISSUE TITLE
Metrics: As an Admin, I want to be able to track the user interaction of Pairings.

### ISSUE THREAD

**Issue by taariq** [PeggyJV/il-loss-charts#111]
As an Admin, I want to be able to track the user interaction of Pairings users so that I know how much demand the app receives and which features are most important to my users.

**Acceptance Criteria**
Add the following metrics to Mixpanel for tracking interactions
1. Number of pair Searches completed on Pairings
2. Number of pairs searched
3. Number of interactions with the Pairings indicators
4. Monthly Active Users (defined by Unique Metamask Connects)

**Comment by kkennis** [comment]
It's in
