### ISSUE TITLE
Typing a Token symbol into the pair selection doesn't work

### ISSUE THREAD

**Issue by zmanian** [PeggyJV/il-loss-charts#2]
<img width="622" alt="Screen Shot 2021-01-04 at 1 00 01 PM" src="https://user-images.githubusercontent.com/93434/103579232-c4dae580-4e8c-11eb-91bc-add09dcd1032.png">

In the market dropdown, I can select a token pair but I can't entire a token pair.

Token pairs don't appear to be sorted in an obvious way and it make it hard to find a token pair.

**Comment by kkennis** [comment]
Should be fixed in `main`
