### ISSUE TITLE
Tokenpair from URL arguments

### ISSUE THREAD

**Issue by zmanian** [PeggyJV/il-loss-charts#3]
It would be good to be able to pass in a token pair like `https://app.sommelier.finance/?KEEP_WETH`

**Comment by kkennis** [comment]
`/pair?id={ethAddress}` works on app.sommelier.finance now - do you think I should add the ability to make it a human-readable string as well? (e.g. `/pair?tokens=KEEP_WETH`)

**Comment by kkennis** [comment]
Both `id={ethAddress}` and `symbol={marketPair}` e.g. `symbol=WETH/USDT` work now.
