### ISSUE TITLE
V3 Subgraph: Define events emitted by Uniswap V3 Core contracts.

### ISSUE THREAD

**Issue by kkennis** [PeggyJV/il-loss-charts#41]
A subgraph is an ETL that ingests events from Ethereum and outputs an indexed database queryable via GraphQL.

This ticket involves the ingestion step; we need to know which events from the Uniswap V3 core contracts are relevant to us.

@jackzampolin has listed the raw events here - https://www.notion.so/Raw-Events-from-v3-core-36384c8c10a74f3f9191747fac244e75 - so this task would involve figuring out which ones are relevant and which ones we might want to track. This will also help us inform our eventual query architecture.

**Acceptance Criteria:**
- List of relevant events from the Uniswap defined in notion, on separate page from 'Raw Events' page

**Comment by jackzampolin** [comment]
Also on github we have a repo: https://github.com/PeggyJV/uniswap-v3-subgraph

**Comment by jackzampolin** [comment]
Closing as complete
