### ISSUE TITLE
V3 Subgraph: Define entities to be indexed by the subgraph.

### ISSUE THREAD

**Issue by kkennis** [PeggyJV/il-loss-charts#42]
Issue #41 will enumerate the events that can are relevant to our data model - this task should actually do the work of defining that data model. This will require looking at prior art - the [Uniswap V2 Subgraph](https://github.com/Uniswap/uniswap-v2-subgraph), and defining the tables to be stored in our database.

Things to think about:
- At least data parity with V2 - may need additional columns to represent e.g. discrete liquidity concepts
- Possible time intervals - V2 supported daily and hourly. We may want to index intervals as tight at 1 minute.
- Should make sure that all entity columns are either directly reflected by or can be derived from the payload of our relevant events.

**Acceptance Criteria**:
- File `schema.graphql` defined in PeggyJV/uniswap-v3-subgraph representing the defined entities

**Comment by jackzampolin** [comment]
Closing as complete
