### ISSUE TITLE
V3 Subgraph: Wire up events to entities and complete subgraph implementation.

### ISSUE THREAD

**Issue by kkennis** [PeggyJV/il-loss-charts#43]
Issues #41 and #42 will have the finished work products of a definition of input data (relevant events from Ethereum), and output data (an entity schema for our processed data). This issue should cover the activity of actually creating the mapping from events to data, and wiring up all supporting services for a working subgraph.

Again, the [Uniswap v2 subgraph](https://github.com/Uniswap/uniswap-v2-subgraph) is a good working template to base this off of.

Work items within this task include:
* Writing the necessary mappings (a.k.a. event handlers) in `src/mappings` to map events to the defined entities.
* Generating and creating a directory for the necessary ABIs to decode the events
* Defining the rules of the subgraph within `subgraph.yaml`, including necessary ABIs, linkings of events to handlers
* Writing package.json to include the necessary scripts: `codegen`, `build`, `create-local`, and `deploy-local`
* Adding linting and prettier to the project (can copy from v2 subgraph)
* Writing a README to describe how to use and deploy this repo, using v2's readme as a template

**Acceptance Criteria**:
- A working repo at PeggyJV/uniswap-v3-subgraph that can be deployed on a local graph node
- Presentation to the Uniswap team for feedback/collaboration

**OUT OF SCOPE**:
- `subgraph.yaml` does not need to define the addresses or starting blocks for indexing the factory contract. This will be added at launch day once they are known, immediately before deploy. Placeholder values can be used.

**Comment by taariq** [comment]
What's the planned release date for the presentation to the Uniswap team?

**Comment by kkennis** [comment]
Monday

**Comment by jackzampolin** [comment]
I believe @kkennis has completed this, closing

**Comment by kkennis** [comment]
In the hands of the Uniswap team now, but the current subgraph works for our purposes.
