### ISSUE TITLE
V3 Subgraph: Set up dedicated graph node infrastructure for V3 subgraph.

### ISSUE THREAD

**Issue by kkennis** [PeggyJV/il-loss-charts#44]
We have graph nodes running in GCP (for instance, currently indexing V2), but for V3 we want a dedicated graph node for reliability's sake. This graph node can share a turbo-geth instance with the other graph nodes - the private IP for this node is available in the Instances section of GCP.

The implementor of this task should create the node, start it, and make it ready for subgraph deployment.

**Acceptance Criteria:**
- Graph node infrastructure set up in GCP, with similar architecture as existing graph nodes (container-optimized OS)
- Graph node instance should also run IPFS
- Easy startup and process management script for the graph node, which includes connection string URLs for postgres, IPFS, and turbogeth
- Proper configuration and tuning, including target block range, pg pool size, and other needed [environment variables](https://github.com/graphprotocol/graph-node/blob/master/docs/environment-variables.md).
- Build toolchain for the graph node, including local Rust and `cargo` environment

**Comment by zmanian** [comment]
Open questions

Should we run open-ethereum and turbo geth or just turbogeth?

Turbo geth and the graph index node have had releases so we should be updating to the latest version.

We should front load all dev ops tasks

**Comment by taariq** [comment]
Question: when is this infra to be delivered?

**Comment by zmanian** [comment]
We should an influx db and the dex agnostic data feeder to the infra requirements for launch.

**Comment by tony-iqlusion** [comment]
I took a look at the managed options for InfluxDB on GCP:

https://www.influxdata.com/products/influxdb-cloud/

> Google Cloud Platform (GCP): US Central (Iowa)

It looks like they're only in `us-central1` which might be a bit problematic from a latency perspective. They had a form to fill out to suggest additional regions and I went ahead and suggested `us-west1`.

**Comment by poldsam** [comment]
Zaki and I were are discussing setting up one (or more) turbogeth nodes dedicated to v3,  based on a current turbogeth snapshot.  Set up a new graph node for it and connect it to a separate PSQL database. Connecting several graph nodes to the same turbogeth has limitations and is likely to slow things down.  

Infrastructure deployment plan for May 5th proposed next steps:

- Set up another turbogeth node
- Take a snapshot of the current turbogeth 
- Set up a new graph node
- Deploy new PSQL database for the graph node
- Connect the price feeder to Influx BD 
- Have the price feeder communicate with the new turbogeth node 

attaching a whiteboard chart with the proposed flow
![IMG_2106](https://user-images.githubusercontent.com/30513716/113637132-c00f0480-9628-11eb-9c3a-278d2206745d.jpg)

**Comment by jackzampolin** [comment]
I believe this is also complete cc @kkennis

**Comment by kkennis** [comment]
Done! Thanks team
