### ISSUE TITLE
API: Define unified, data-source-agnostic data model for economic events on DEXes with Bitquery

### ISSUE THREAD

**Issue by kkennis** [PeggyJV/il-loss-charts#46]
After our Blep and V2 integrations, we have a sense of what different data models for indexing DEXes might look like. It's time to define our own. This is a big part of leadership and our competitive data moat: we should be opinionated about the best ways to model these facts, and be able to collect data from disparate data sources and unify them into one coherent entity structure that we've defined.

To make this happen, we need to define what this data model looks like. We should take inspiration from the Graph and Blep, but it does not to necessarily be the same - it's likely that we can improve, and provide convenient derived properties on the data that are built of our data primitives. For example: a 7-day moving average of price.

We should define these data models in two ways: 1) as TypeScript interfaces, and 2) as TypeScript classes, which implement those interfaces, and provide additional convenience methods on top. These methods should be read-only as we should consider our data immutable once fetched. See `packages/sommelier-types/src/pair.ts` for an example of this pattern.

**Acceptance Criteria:**
- Data model defined in `packages/sommelier-types`
- Documentation in `sommelier-types/README` on data model

**Comment by zmanian** [comment]
the first thing I want is data model of what is needed for the app to make a template or recommendation.

I'm thinking things like 

1. Spot price
2. moving averages?
3. Std deviation

What else?

Our goal is Uniswap V3 add liquidity. What data backs what templates are shown to a user?

**Comment by kkennis** [comment]
Put this in a PG table

**Comment by zmanian** [comment]
@tony-iqlusion Do you have any view if this should use a message queue of some sort or a Postgres table?

**Comment by tony-iqlusion** [comment]
I don't have a complete picture of the problem, but I think it might make sense to try to get an end-to-end spike in the simplest way possible, be that a single app and something like a Postgres database or what have you, and then when we have a more concrete view of the problem and running code, look at the various GCP offerings and decide which is the best fit.

There are a number of different ways to store and propagate this sort of data on GCP. Offhand it sounds like a financial timeseries data problem, and there are a number of possible ways to model that. Some options beyond Cloud SQL are:

- [Bigtable](https://cloud.google.com/bigtable/docs/schema-design-time-series)
- [Pub/Sub](https://cloud.google.com/pubsub)
- [Memorystore](https://cloud.google.com/memorystore)

Probably the biggest question here is historical data: does it matter? Or is this effectively operating over a sliding window where things like latency are more important than historical retention?

**Comment by zmanian** [comment]
The current design to have a sliding window over multiple source that produce data in the common schema.

**Comment by zmanian** [comment]
Okay here are my updated thoughts.

We need a feeder app that be pointed either our turbogeth or api provider like Alchemy.

The feeder should have a mode where it calls the uniswap v2 router contract and iterates over the all the pairs in the router and populates a table with all 30,000+ pairs.


For each pair, we should generate a price sample for each unit of time buy checking the reserves of each contract in the index.

Another related thought is running a Hasura instance on this table to expose a graphql interface

**Comment by tony-iqlusion** [comment]
Curious if we could deploy a GraphQL server to GCP Cloud Functions. I guess it depends whether or not you care about subscriptions, which wouldn't fit a "serverless" model.

I found this for Hasura (not really familiar with it otherwise), but it looks out-of-date (archived) and only seems to cover database event triggers:

https://github.com/hasura/cloud-functions-boilerplates/tree/master/google-cloud-functions

Edit: here's an integration between Apollo and GCF:

https://www.npmjs.com/package/apollo-server-cloud-functions

**Comment by jackzampolin** [comment]
Ok, reading through this it looks like we need the following pieces:
- Indexer/feeder which queries ETH style nodes and pulls the data out
- A database (either SQL or a timeseries solution) (if we go with something thats not SQL we couldn't use the graphql server)
- A graphql or other server for pushing the data to clients

**Comment by kkennis** [comment]
This is being handled by https://github.com/PeggyJV/dextick. Will close this issue once we have a successful integration

**Comment by kkennis** [comment]
Adapting this ticket to focus on the bitquery integration work
