### ISSUE TITLE
API: Write v3 subgraph client

### ISSUE THREAD

**Issue by kkennis** [PeggyJV/il-loss-charts#47]
Once #42 is completed, we will know the query interface for our subgraph. Even before the subgraph is deployed, we should use these definitions to write our API client for the subgraph. This client should be responsible for querying the subgraph and transforming the data (if necessary) into the data types defined in #46.

This should follow a similar pattern to the v2 client described in `packages/server/src/services/uniswap.ts`. 

In other words, it should:
* Be scoped to a single file
* Export a stateless query interface
* Define query API for each data type, including query parameters (limits/timestamps)
* Support the same queries as the V2 subgraph
* Do basic error handling (handle non-success status codes or malformed responses and throw errors)

In the future, we may expand or modify the queries, but getting to feature parity with V2 is a good place to start.

**Acceptance Criteria:**
- File `packages/server/src/services/uniswap-v3.ts` exists in the API codebase
- V3 integration exposes same API as v2 service
- All queries to the V3 subgraph implemented

**Comment by kkennis** [comment]
Example GraphQL API for v3: http://35.197.14.14:8000/subgraphs/name/sommelier/uniswap-v3/graphql

**Comment by khcoaching** [comment]
Completed
