### ISSUE TITLE
API: Create route to list available v3 pools

### ISSUE THREAD

**Issue by kkennis** [PeggyJV/il-loss-charts#48]
We need to expose a route on the API to list all Uniswap V3 pools. It should accept the parameter `count` and `sort` - one should be able to get a specific number of results via `count` (max 1000) and sort by either `volumeUSD` (highest-volume pools) or `reserveUSD` (highest-liquidity pools).

The route should then use the proper subgraph call exposed by the V3 integration written in #47 to fetch this data, and return it to the client. The route should also perform parameter validation.

**Acceptance Criteria:**
- Route exposed to get top pairs for v3
- Route validates `0 < count < 1001`
- Route validates `sort=volumeUSD | sort=reserveUSD`
- Route defaults to `count=100` and `sort=volumeUSD`
- Route returns an array of top pairs on Uniswap V3, with all pair metadata according to our defined data model
- API Integration tests written for route

**Comment by kkennis** [comment]
Metrics for pools: % change in liquidity over some time window, rate of liquidity change over volume

**Comment by khcoaching** [comment]
Completed
