### ISSUE TITLE
API: Create route to get details of a certain pool

### ISSUE THREAD

**Issue by kkennis** [PeggyJV/il-loss-charts#49]
Akin to our v2 route `/api/v1/uniswap/pairs/:pairId`, we need a route for V3 to get greater details on a specific pair and associated metrics. This route should contain as-close-to-real-time as possible data about the pair, for powering pair details and Add Liquidity experiences in the UI.

This route may also have to calculate some derived stats based on available data and provide those as pair insights. We want _at least_ the below stats:
* Contract address of the pool
* Current price of pool
* Liquidity distribution of pool
* Number of unique liquidity providers in pool
* Fee tier of pool
* Creation date of pool
* Trade volume of pool in notional USD value
* Trade volume of pool in # of trades
* Trade distribution of pool
* Current reserves of each asset in pool
* Metadata about each token in the pool (address, decimals, symbol, long name)

As with v2, the API route should validate that the passed `id` is a valid ETH address, and should return appropriate error events if the pool could not be found.

**Acceptance Criteria:**

* Route exposed to get pair details for v3
* Route validates pairId is a valid ETH address
* Route returns pair details with fields specified above
* API Integration tests written for route

**Comment by khcoaching** [comment]
Completed
