### ISSUE TITLE
API: Create route to get historical data for a pair

### ISSUE THREAD

**Issue by kkennis** [PeggyJV/il-loss-charts#50]
Akin to our v2 API, we need to get historical data for a pair. Unlike our V2 API, we do not need to split this into different routes, but we likely want a time window query parameter, since in V3 we will have a greater range of time window aggregations.

This route should return the same data structure as in #49, but across a time series, specified in `from` and `to` parameters. Both `from` and `to` should be optional, which `from` defaulting to the creation date of the pool, and `to` defaulting to the current timestamp.

This route will help us populate charts and other UIs on the frontend, and we might also want to calculate time-series specific statistics. However it should not perform any calculations over the data - this should provide raw results only, with calculations provided in a different route.

Acceptance Criteria:

* Route exposed to get time series data for a pool for v3
* Route validates `startDate` is a valid timestamp
* Route validates `endDate` is a valid timestamp
* Route validates `window` depending on available windows (decided by subgraph) - `window` should default to `1d`
* Route returns an array of time series data for the specified pool, with all pair metadata specified as in #49
* API Integration tests written for route

**Comment by khcoaching** [comment]
Completed
