### ISSUE TITLE
UX: Strategy Determination

### ISSUE THREAD

**Issue by kkennis** [PeggyJV/il-loss-charts#54]
The core to the 'simplifying LPing' experience on Sommelier for V3 Uniswap is strategy suggestion. Non-sophisticated LPs don't have the knowhow of resources to figure out economically optimal liquidity provision on their own, especially for pairs of floating price (e.g., non-stablecoin pairs). Sommelier will offer some basic strategies to help suggest how users might provision their liquidity.

We should aim for 3 data-driven strategies at launch. These do **not** need to be the ultimately economically optimal strategies, but should be unequivocally better than providing liquidity across the entire price curve. They will also not be self-updating, as they will exist without the help of a protocol.

Here are some basic strategies:
- Provide liquidity within 1 7-day standard deviation of current mid-price
- Provide liquidity that captures 80% of the trade distribution over the past 7 days
- Provide liquidity between the 7-day low and 7-day high price
- Provide liquidity at the mid price +/- 20%

The implementor of this task should decide on three strategies, document them, show how they can be calculated from our available data, and make a (simple) economic argument for their utility. The team can then review these strategies.

**Acceptance Criteria:**

- Three chosen strategies document on Notion and approved by the team

**Comment by jackzampolin** [comment]
I think we had a discussion that we are only going with 1 strategy. Discuss in standup today

**Comment by kkennis** [comment]
We chose a strategy, will be implementing
