### ISSUE TITLE
V3 Subgraph: Uniswap Team Communication

### ISSUE THREAD

**Issue by kkennis** [PeggyJV/il-loss-charts#57]
Roadmap for communication re: Subgraph development.

**Monday 4/2:**
* **COMMS:** Kevin to present entity schema to Uniswap team for _core_ contract functionality (position data)
* **DEPENDENCY:** can we open up uniswap-v3-core-subgraph repo to Uniswap team?

Comms work lead to two work streams:
* A set of actionable entities we can start implementing mappings for core
* A set of entities we will need to iterate on based on feedback for core

**Monday 4/2-Thursday 4/7:**
* **DEVELOPMENT:** Kevin to implement mappings for actionable entities

Development work will lead us to Milestone 1: having a partial core subgraph deployed.

**Thursday 4/7:**
* **COMMS:** Kevin to present a live, deployed, queryable subgraph containing **actionable entities** for **core contracts only**, deployed against Uniswap's private testnet for feedback
* **DEVELOPMENT:** Kevin to use feedback to finalize and implement mappings for the rest of the core entities

Comms work will help us iterate on the deployed subgraph towards finalization on 4/12.
Development work will lead us to Milestone 2: having a the full core subgraph deployed.

**Monday 4/12:**
* **RELEASE:** Uniswap V3 core entities fully deployed to private testnet
* **COMMS:** Kevin to present entity schema to Uniswap team for _periphery_ contract functionality (position data)

Comms work lead to two work streams:
* A set of actionable entities we can start implementing mappings for periphery
* A set of entities we will need to iterate on based on feedback for periphery

**Monday 4/12-Thursday 4/15:**
* **DEVELOPMENT:** Uniswap v3 periphery mappings to be iterated upon, implemented and deployed to private testnet

Development work will lead us to Milestone 3: having both finalized periphery and core subgraphs deployed.

**Friday 4/16:**
* **RELEASE:** Full uniswap v3 subgraphs for both core and periphery finalized and deployed to private testnet, modulo small tweaks

**Comment by taariq** [comment]
Thank you for this roadmap. It's very helpful to understand what's coming next.

**Comment by kkennis** [comment]
@jackzampolin can you take a look and ACK this timeline+comms plan when you get a chance, I know we have both been active in the Uniswap channel so want to make sure we have a unified plan as far as promising and delivering

**Comment by jackzampolin** [comment]
I think the periphery stuff is a bit premature to put timelines on that will depend on the call with the uniswap team next week. I can provide access to the uniswap team, just need some GH handles.

LETS GOOOO 🚀

**Comment by kkennis** [comment]
Yeah, I'm being optimistic here on the periphery stuff, but in light of other dependencies we should definitely shoot to finalize the subgraph by April 15th if at all possible. We may need to do some small tweaks after that, of course, and if the Uniswap team decides to change the periphery interface, we will have to adjust

**Comment by jackzampolin** [comment]
We have done our part here. Completing this ticket is blocked on the uniswap team.

**Comment by kkennis** [comment]
I think this is OK to close, given like Jack said that we've done our part.
